---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable

Layout/LineLength:
  Max: 123
  Exclude:
    - 'lib/gitlab/client/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  MaxOptionalParameters: 4

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/gitlab/*'
    - 'lib/gitlab/client/*'

Lint/NonDeterministicRequireOrder:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/FilePath:
  Enabled: false
