#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

# Exit cleanly from an early interrupt
Signal.trap('INT') { exit 1 }

require 'gitlab/cli'

Gitlab::CLI.start(ARGV)
